CSC = {
    "3IE": "Ireland (Three)",
    "ACG": "USA (Nextech / C-Spire",
    "ACR": "Saudi Arabia",
    "AFG": "Afghanistan",
    "AFR": "Kenya",
    "AIO": "USA (Cricket)",
    "ALE": "Ecuador",
    "AMN": "Spain (Orange)",
    "AMO": "Spain (Orange)",
    "ANC": "Argentina",
    "ANP": "Ireland",
    "ARO": "Argentina",
    "ATL": "Spain (Vodafone)",
    "ATO": "Austria (Open)",
    "ATT": "USA (AT&T)",
    "AUT": "Switzerland",
    "AVF": "Albania (Vodafone)",
    "BAT": "Mexico",
    "BGL": "Bulgaria",
    "BHT": "Bosnia and Herzegovina (BH TELECOM)",
    "BMC": "Canada (Bell Mobile)",
    "BNG": "Bangladesh",
    "BOG": "France (Bouygues)",
    "BRI": "Taiwan",
    "BST": "USA (Boost Mobile)",
    "BTC": "Libya",
    "BTU": "United Kingdom",
    "BVO": "Bolivia",
    "BVT": "Bolivia",
    "BVV": "Bolivia",
    "BWA": "Canada (SaskTel)",
    "CAC": "Uzbekistan",
    "CAM": "Cambodia",
    "CAU": "Caucasus Countries",
    "CCT": "USA (Xfinity Mobile (Comcast))",
    "CDR": "Dominican Republic",
    "CEL": "Israel (Cellcom)",
    "CGU": "Guatemala (Tigo)",
    "CHA": "USA (Spectrum Mobile (Charter))",
    "CHC": "China (Open China)",
    "CHE": "Chile (Entel PCS)",
    "CHL": "Chile (Claro)",
    "CHM": "China (China Mobile)",
    "CHN": "China",
    "CHO": "Chile",
    "CHR": "Canada (Chatr Mobile)",
    "CHT": "Chile (Telefonica)",
    "CHV": "Chile (VTR)",
    "CHX": "Chile (Nextel)",
    "CNX": "Romania (Vodafone)",
    "COA": "Romania (Cosmote)",
    "COB": "Colombia (Movistar)",
    "COE": "Colombia (ETB)",
    "COL": "Colombia",
    "COM": "Colombia (Comcel)",
    "COO": "Colombia",
    "COS": "Greece (Cosmote)",
    "CPA": "Panama (Claro)",
    "CPW": "United Kingdom (Carphone Warehouse)",
    "CRC": "Chile",
    "CRG": "Croatia",
    "CRM": "South America (Moviestar)",
    "CRO": "Croatia (T-Mobile)",
    "CTC": "China (China Telecom)",
    "CTE": "Honduras",
    "CTI": "Argentina (Claro)",
    "CTP": "Paraguay (Claro)",
    "CTU": "Uruguay (Claro)",
    "CWT": "Taiwan",
    "CWW": "Jamaica",
    "CYO": "Cyprus (Cytamobile Vodafone)",
    "CYV": "Cyprus (Vodafone)",
    "DBT": "Germany",
    "DDE": "Germany (Congstar)",
    "DHR": "Croatia (Bonbon)",
    "DNL": "Netherlands (Ben NL)",
    "DOO": "Dominican Republic",
    "DOR": "Dominican Republic (Orange)",
    "DPL": "Poland (Heyah)",
    "DRE": "Austria (3 Hutchison)",
    "DTM": "Germany (T-Mobile)",
    "EBE": "Ecuador",
    "ECO": "Ecuador",
    "ECT": "Nigeria",
    "EGY": "Egypt",
    "EIR": "Ireland (eMobile)",
    "EON": "Trinidad and Tobago",
    "EPL": "Germany (E-Plus)",
    "ERA": "Poland (T-Mobile)",
    "ERO": "Bosnia and Herzegovina",
    "ESK": "Canada (EastLink)",
    "ETE": "El Salvador",
    "ETL": "Czech Republic",
    "ETR": "Bangladesh",
    "EUR": "Greece",
    "EVR": "United Kingdom (EE)",
    "FMC": "Canada (Fido Mobile)",
    "FOP": "Spain",
    "FTB": "France",
    "FTM": "France (Orange)",
    "GBL": "Bulgaria",
    "GCF": "Global Certification Forum",
    "GLB": "Philippines (Globe)",
    "GLW": "Canada (Globalive Wind Mobile)",
    "H3G": "United Kingdom (H3G)",
    "HAT": "Romania",
    "HTS": "Sweden (Tre)",
    "HUI": "Italy (H3G)",
    "HUT": "Australia ( Three/Vodafone)",
    "ICE": "Costa Rica",
    "IDE": "Poland (Orange)",
    "ILO": "Israel",
    "INS": "India",
    "INU": "India",
    "IRD": "Slovakia (Orange)",
    "ITV": "Italy",
    "IUS": "Mexico",
    "JDI": "Jamaica",
    "JED": "Saudi Arabia",
    "KDO": "Canada (Koodo Mobile)",
    "KEN": "Kenya",
    "KPN": "Netherlands (KPN)",
    "KSA": "Saudi Arabia",
    "KTC": "Korea (KT Corporation)",
    "LRA": "USA (Bluegrass Cellular)",
    "LUC": "Korea (LG Uplus)",
    "LUX": "Luxembourg",
    "LYS": "Libya",
    "MAT": "Morocco (MAT)",
    "MAX": "Austria (T-Mobile)",
    "MBM": "Macedonia (T-Mobile)",
    "MED": "Morocco",
    "MEO": "Portugal",
    "MET": "Ireland (Meteor)",
    "MID": "Iraq",
    "MM1": "Singapore",
    "MOB": "Austria (A1)",
    "MOT": "Slovenia (Mobitel)",
    "MOZ": "Switzerland",
    "MRU": "Mauritius",
    "MSR": "Serbia (Telenor)",
    "MTB": "Canada (Belarus)",
    "MTL": "Bulgaria (MTL)",
    "MTZ": "Zambia (MTN Zambia)",
    "MWD": "Morocco (MWD)",
    "MXO": "Mexico",
    "NBS": "South America (Open Line)",
    "NEE": "Nordic countries",
    "NPL": "Nepal",
    "NRJ": "France",
    "NZC": "New Zealand",
    "O2C": "Czech Republic (O2C)",
    "O2I": "Ireland O2",
    "O2U": "United Kingdom (O2)",
    "OMN": "Italy (Vodafone)",
    "ONE": "Austria",
    "OPS": "Australia (Optus)",
    "OPT": "Portugal (Optimus)",
    "ORA": "United Kingdom (Orange)",
    "ORC": "France",
    "ORG": "Switzerland",
    "ORN": "France",
    "ORO": "Romania (Orange)",
    "ORS": "Slovakia",
    "ORX": "Slovakia",
    "PAK": "Pakistan (PAK)",
    "PAN": "Hungary (Telenor)",
    "PBS": "Panama",
    "PCL": "Israel (Pelephone)",
    "PCT": "Puerto Rico",
    "PCW": "Panama (Cable & Wireless)",
    "PET": "Peru",
    "PGU": "Guatemala",
    "PHB": "Belgium",
    "PHE": "Spain",
    "PHN": "Netherlands",
    "PLS": "Poland (PLUS)",
    "PNG": "Papua New Guinea",
    "PNT": "Peru (Nextel)",
    "PRO": "Belgium (Proximus)",
    "PRT": "Poland (Play)",
    "PSN": "Argentina (Personal)",
    "PSP": "Paraguay (Personal)",
    "PTR": "Israel (Orange/Partner)",
    "PVT": "Peru (Viettel)",
    "ROM": "Romania",
    "RWC": "Canada (Rogers)",
    "SAM": "Peru (SAM)",
    "SEB": "Baltic",
    "SEE": "South East Europe",
    "SEK": "Ukraine (Kyivstar)",
    "SER": "Russia",
    "SFR": "France (SFR)",
    "SIM": "Slovenia (Si.mobil)",
    "SIN": "Singapore (SingTel)",
    "SIO": "Slovakia",
    "SKC": "Korea (SK Telecom)",
    "SKZ": "Kazakhstan",
    "SLK": "Sri Lanka",
    "SMA": "Philippines (Smart)",
    "SMO": "Serbia",
    "SPR": "USA (Sprint (CDMA))",
    "STH": "Singapore (StarHub)",
    "SUN": "Switzerland",
    "SWC": "Switzerland (Swisscom)",
    "TCE": "Mexico (Telcel)",
    "TCL": "Portugal (Vodafone)",
    "TDC": "Denmark",
    "TEB": "Bosnia and Herzegovina",
    "TEL": "Australia (Telstra)",
    "TEN": "Norway (Telenor)",
    "TFN": "USA (Tracfone)",
    "TGP": "Paraguay (Tigo)",
    "TGU": "Guatemala",
    "TGY": "Hong Kong",
    "THL": "Thailand",
    "THR": "Iran",
    "TIM": "Italy (TIM)",
    "TLS": "Canada (Telus)",
    "TMB": "USA (T-Mobile)",
    "TMC": "Algeria",
    "TMH": "Hungary (T-mobile)",
    "TMK": "USA (MetroPCS)",
    "TML": "Bangladesh",
    "TMM": "Mexico (Movistar)",
    "TMN": "Portugal (TMN)",
    "TMS": "Slovakia",
    "TMT": "Montenegro",
    "TMU": "United Kingdom (T-Mobile)",
    "TMZ": "Czech Republic (T-Mobile)",
    "TNL": "Netherlands (T-Mobile)",
    "TNZ": "New Zealand",
    "TOP": "Serbia (VIP)",
    "TPA": "Panama",
    "TPD": "Netherlands",
    "TPH": "Portugal (TPH)",
    "TPL": "Poland (T-mobile)",
    "TRA": "Croatia",
    "TRC": "Turkey",
    "TRG": "Austria (Telering)",
    "TSI": "Ireland",
    "TSR": "Serbia (Telekom)",
    "TTR": "Austria",
    "TTT": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TWO": "Croatia (TELE2)",
    "UFN": "Argentina (Movistar)",
    "UFU": "Uruguay",
    "UPO": "Uruguay",
    "USC": "US Cellular",
    "UYO": "Uruguay",
    "VAU": "Australia (Vodafone)",
    "VD2": "Germany (Vodafone)",
    "VDC": "Czech Republic (Vodafone)",
    "VDF": "Netherlands (Vodafone)",
    "VDH": "Hungary Vodafone",
    "VDI": "Ireland (Vodafone)",
    "VDS": "Sweden",
    "VFJ": "Fiji (Vodafone)",
    "VGF": "France",
    "VGR": "Greece (Vodafone)",
    "VIA": "Germany (O2)",
    "VIM": "Macedonia",
    "VIP": "Croatia (VIPNET)",
    "VIR": "United Kingdom",
    "VMC": "Virgin Mobile Canada",
    "VMU": "Virgin Mobile USA",
    "VNZ": "New Zealand (Vodafone)",
    "VOD": "United Kingdom (Vodafone)",
    "VTR": "Canada (Videotron)",
    "VVT": "Bulgaria (VVT)",
    "VZW": "USA (Verizon)",
    "WAN": "Taiwan",
    "WIN": "Italy (Wind)",
    "WTL": "Saudi Arabia",
    "XAA": "USA (Unbranded/Unlocked)",
    "XAC": "Canada (Unbranded)",
    "XAG": "USA (Tracfone)",
    "XAR": "Cellular South US",
    "XAS": "USA (Unbranded/Unlocked)",
    "XEB": "Belgium",
    "XEC": "Spain (Movistar)",
    "XEE": "Sweden",
    "XEF": "France",
    "XEG": "Germany (1&1)",
    "XEH": "Hungary",
    "XEN": "Netherlands",
    "XEO": "Poland",
    "XEU": "United Kingdom / Ireland",
    "XEZ": "Czech Republic",
    "XFA": "South Africa",
    "XFC": "South Africa",
    "XFE": "South Africa",
    "XFM": "South Africa",
    "XFU": "Saudi Arabia (STC)",
    "XFV": "South Africa (Vodafone)",
    "XID": "Indonesia",
    "XME": "Malaysia",
    "XSA": "Australia",
    "XSE": "Indonesia",
    "XSG": "United Arab Emirates",
    "XSO": "Singapor (Singtel)",
    "XSP": "Singapore",
    "XSS": "United Arab Emirates",
    "XTC": "Philippines (Open Line)",
    "XTE": "Philippines (Sun Cellular)",
    "XXV": "Vietnam",
    "YOG": "Spain (Yoigo)",
    "ZTA": "Brazil (Claro)",
    "ZTM": "Brazil (TIM)",
    "ZTO": "Brazil",
    "ZTR": "Brazil (Oi)",
    "ZVV": "Brazil (VIVO)"
}